[platformio]
extra_configs = variants/*/platformio.ini

[common]
lib_deps =
	jgromes/RadioLib @ 7.7.1
    #https://github.com/ESP32Async/AsyncTCP.git#v3.3.8
    #https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.7.4
    #ayushsharma82/ElegantOTA @ 3.1.7

build_flags =
    -I variants/${PIOENV}
	-D RADIOLIB_EXCLUDE_CC1101=1
	-D RADIOLIB_EXCLUDE_LR11X0=1
	-D RADIOLIB_EXCLUDE_LR2021=1
	-D RADIOLIB_EXCLUDE_NRF24=1
	-D RADIOLIB_EXCLUDE_RF69=1
	-D RADIOLIB_EXCLUDE_RFM2X=1
	-D RADIOLIB_EXCLUDE_SI443X=1
	-D RADIOLIB_EXCLUDE_SX1231=1
	-D RADIOLIB_EXCLUDE_SX1233=1
	-D RADIOLIB_EXCLUDE_SX126X=1
	-D RADIOLIB_EXCLUDE_SX127X=1
	-D RADIOLIB_EXCLUDE_SX128X=1
	-D RADIOLIB_EXCLUDE_AFSK=1
	-D RADIOLIB_EXCLUDE_APRS=1
	-D RADIOLIB_EXCLUDE_AX25=1
	-D RADIOLIB_EXCLUDE_BELL=1
	-D RADIOLIB_EXCLUDE_FSK4=1
	-D RADIOLIB_EXCLUDE_HELLSCHREIBER=1
	-D RADIOLIB_EXCLUDE_LORAWAN=1
	-D RADIOLIB_EXCLUDE_MORSE=1
	-D RADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
	-D RADIOLIB_EXCLUDE_RTTY=1
	-D RADIOLIB_EXCLUDE_SSTV=1
    #-DELEGANTOTA_USE_ASYNC_WEBSERVER=1

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
